<?php

$F40 =  '<a href="?forum=40">40+</a>-mod';
$F80 =  '<a href="?forum=80S">80S</a>-mod';
$AEX = '<a href="?forum=AEX">AEX</a>-mod';
$BH  =  '<a href="?forum=BH">B&H</a>-mod';
$BNW = '<a href="?forum=BNW">BNW</a>-mod';
$CH  =  '<a href="?forum=CH">C&H</a>-mod';
$CRE = '<a href="?forum=CRE">CRE</a>-mod';
$CUL = '<a href="?forum=CUL">CUL</a>-mod';
$DEF = '<a href="?forum=DEF">DEF</a>-mod';
$DGK = '<a href="?forum=DGK">DGK</a>-mod';
$DIG = '<a href="?forum=DIG">DIG</a>-mod';
$EK  =   '<a href="?forum=EK">EK</a>-mod';
$ESF = '<a href="?forum=ESF">ESF</a>-mod';
$EXA = '<a href="?forum=EXA">EXA</a>-mod';
$FF  =  '<a href="?forum=FF">F&F</a>-mod';
$FL  =  '<a href="?forum=FL">F&L</a>-mod';
$FEE  = '<a href="?forum=FF">FEE</a>-mod';
$FHF = '<a href="?forum=FHF">FHF</a>-mod';
$FLU = '<a href="?forum=FLU">FLU</a>-mod';
$FMM = '<a href="?forum=FMM">FMM</a>-mod';
$FOT = '<a href="?forum=FOT">FOT</a>-mod';
$FVZ = '<a href="?forum=FVZ">FVZ</a>-mod';
$GAM = '<a href="?forum=GAM">GAM</a>-mod';
$GC  =   '<a href="?forum=GC">GC</a>-mod';
$IDO = '<a href="?forum=IDO">IDO</a>-mod';
$IND = '<a href="?forum=IND">IND</a>-mod';
$INT = '<a href="?forum=INT">INT</a>-mod';
$JNG = '<a href="?forum=JNG">JNG</a>-mod';
$KW  =  '<a href="?forum=KW">K&W</a>-mod';
$KAA = '<a href="?forum=KAA">KAA</a>-mod';
$KEL = '<a href="?forum=KEL">KEL</a>-mod';
$KLB = '<a href="?forum=KLB">KLB</a>-mod';
$KPD = '<a href="?forum=KPD">KPD</a>-mod';
$KSW = '<a href="?forum=KSW">KSW</a>-mod';
$LIF = '<a href="?forum=LIF">LIF</a>-mod';
$LEF = '<a href="?forum=LEF">LEF</a>-mod';
$LWL = '<a href="?forum=LWL">LWL</a>-mod';
$MEN = '<a href="?forum=MEN">MEN</a>-mod';
$MLN = '<a href="?forum=MLN">MLN</a>-mod';
$MO =    '<a href="?forum=MO">MO</a>-mod';
$MUZ = '<a href="?forum=MUZ">MUZ</a>-mod';
$NIN = '<a href="?forum=NIN">NIN</a>-mod';
$NWB = '<a href="?forum=NWB">NWB</a>-mod';
$NWS = '<a href="?forum=NWS">NWS</a>-mod';
$ONZ = '<a href="?forum=ONZ">ONZ</a>-mod';
$OUD = '<a href="?forum=OUD">OUD</a>-mod';
$POL = '<a href="?forum=POL">POL</a>-mod';
$PTA = '<a href="?forum=PTA">PTA</a>-mod';
$PUB = '<a href="?forum=PUB">PUB</a>-mod';
$RBO = '<a href="?forum=RBO">RBO</a>-mod';
$REV = '<a href="?forum=REV">REV</a>-mod';
$RP  =  '<a href="?forum=RP">R&P</a>-mod';
$ROL = '<a href="?forum=ROL">ROL</a>-mod';
$ROO = '<a href="?forum=ROO">ROO</a>-mod';
$RLS = '<a href="?forum=RLS">RLS</a>-mod';
$SER = '<a href="?forum=SER">SER</a>-mod';
$SES = '<a href="?forum=SES">SES</a>-mod';
$SEX = '<a href="?forum=SEX">SEX</a>-mod';
$SHO = '<a href="?forum=SHO">SHO</a>-mod';
$SPT = '<a href="?forum=SPT">SPT</a>-mod';
$STA = '<a href="?forum=STA">STA</a>-mod';
$TAL = '<a href="?forum=TAL">TAL</a>-mod';
$TDF = '<a href="?forum=TDF">TDF</a>-mod';
$TRU = '<a href="?forum=TRU">TRU</a>-mod';
$TRV = '<a href="?forum=TRV">TRV</a>-mod';
$TTK = '<a href="?forum=TTK">TTK</a>-mod';
$TV  =   '<a href="?forum=TV">TV</a>-mod';
$US  =   '<a href="?forum=US">US</a>-mod';
$UVT = '<a href="?forum=UVT">UVT</a>-mod';
$VA  =  '<a href="?forum=VA">V&A</a>-mod';
$VBL = '<a href="?forum=VBL">VBL</a>-mod';
$VKZ = '<a href="?forum=VBL">VKZ</a>-mod';
$WT  =  '<a href="?forum=WT">W&T</a>-mod';
$WGR = '<a href="?forum=WGR">WGR</a>-mod';
$WKN = '<a href="?forum=WKN">WKN</a>-mod';
$ZOM = '<a href="?forum=ZOM">ZOM</a>-mod';


$ui_99999   		= '<img alt="" style="width: 60px; height: 60px;" src="ui/99999.gif">';
$ui_ajacied4lf   	= '<img alt="" style="width: 60px; height: 60px;" src="ui/ajacied4lf.gif">';
$ui_Anne   			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Anne.gif">';
$ui_arachide  		= '<img alt="" style="width: 60px; height: 60px;" src="ui/arachide.gif">';
$ui_APK		  		= '<img alt="" style="width: 60px; height: 60px;" src="ui/APK.jpg">';
$ui_Automatic_Rock  = '<img alt="" style="width: 60px; height: 60px;" src="ui/Automatic_Rock.jpg">';
$ui_Bart   			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Bart.png">';
$ui_belsen 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/belsen.jpg">';
$ui_boemdikkie		= '<img alt="" style="width: 60px; height: 60px;" src="ui/boem-dikkie.png">';
$ui_Bosbeetle 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Bosbeetle.gif">';
$ui_Brighteyes 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Brighteyes.gif">';
$ui_Cat22 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Cat22.png">';
$ui_Cobra4 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Cobra4.jpg">';
$ui_Copycat			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Copycat.gif">';
$ui_DaMart 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/DaMart.gif">';
$ui_Dark_Angelus	= '<img alt="" style="width: 60px; height: 60px;" src="ui/Dark_Angelus.gif">';
$ui_De_Taartjesfee	= '<img alt="" style="width: 60px; height: 60px;" src="ui/De_Taartjesfee.gif">';
$ui_debuurvrouw		= '<img alt="" style="width: 60px; height: 60px;" src="ui/debuurvrouw.jpg">';
$ui_du_ke			= '<img alt="" style="width: 60px; height: 60px;" src="ui/du_ke.gif">';
$ui_Dubbeldrank		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Dubbeldrank.gif">';
$ui_Fendy			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Fendy.jpg">';
$ui_Ferdo			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Ferdo.jpg">';
$ui_Five_Horizons	= '<img alt="" style="width: 60px; height: 60px;" src="ui/Five_Horizons.gif">';
$ui_Fopje  			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Fopje.gif">';
$ui_Frank_Drebin	= '<img alt="" style="width: 60px; height: 60px;" src="ui/Frank_Drebin.jpg">';
$ui_Friek_			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Friek_.jpg">';
$ui_Frutsel	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Frutsel.jpg">';
$ui_GGMM	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/GGMM.jpg">';
$ui_HeaN82	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/HeaN82.gif">';
$ui_HeatWave 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/HeatWave.jpg">';
$ui_HetKlusKonijn	= '<img alt="" style="width: 60px; height: 60px;" src="ui/HetKlusKonijn.jpg">'; 
$ui_Hexagon 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Hexagon.jpg">';
$ui_Houniet 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Houniet.jpg">';
$ui_iBenny 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/iBenny.png">';
$ui_IHVK 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/IHVK.jpg">';
$ui_JDude 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/JDude.jpg">';
$ui_jitzzzze		= '<img alt="" style="width: 60px; height: 60px;" src="ui/jitzzzze.jpg">';
$ui_Kaas		    = '<img alt="" style="width: 60px; height: 60px;" src="ui/Kaas-.jpg">';
$ui_kanovinnie	    = '<img alt="" style="width: 60px; height: 60px;" src="ui/kanovinnie.jpg">';
$ui_Karina		    = '<img alt="" style="width: 60px; height: 60px;" src="ui/Karina.png">';
$ui_Lavenderr	    = '<img alt="" style="width: 60px; height: 60px;" src="ui/Lavenderr.jpg">';
$ui_LethalNinja	    = '<img alt="" style="width: 60px; height: 60px;" src="ui/LethalNinja.gif">';
$ui_liesje1979	    = '<img alt="" style="width: 60px; height: 60px;" src="ui/liesje1979.jpg">';
$ui_LittleBrownie	= '<img alt="" style="width: 60px; height: 60px;" src="ui/LittleBrownie.gif">';
$ui_Lois 		    = '<img alt="" style="width: 60px; height: 60px;" src="ui/Lois.gif">';
$ui_LompeHork		= '<img alt="" style="width: 60px; height: 60px;" src="ui/LompeHork.gif">';
$ui_Lotusss			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Lotusss.jpg">';
$ui_Lutte   		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Lutte.png">';
$ui_Magneet  		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Magneet.jpg">';
$ui_Maharbal 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Maharbal.jpg">';
$ui_Maisnon  		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Maisnon.gif">';
$ui_Marie30  		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Marie30.jpg">';
$ui_Mike   			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Mike.jpg">';
$ui_MissBliss		= '<img alt="" style="width: 60px; height: 60px;" src="ui/MissBliss.gif">';
$ui_Misstique 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Misstique.jpg">';
$ui_Mletje 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Ml-etje.jpg">';
$ui_Mortaxx			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Mortaxx.jpg">';
$ui_motorbloempje 	= '<img alt="" style="width: 60px; height: 60px;" src="ui/motorbloempje.png">';
$ui_murp	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/murp.gif">';
$ui_Mylene	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Mylene.gif">';
$ui_Natalie	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Natalie.gif">';
$ui_Nibbit	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Nibb-it.jpg">';
$ui_NJ		 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/NJ.gif">';
$ui_Oerbeer	 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Oerbeer.png">';
$ui_Ole		 		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Ole.jpg">';
$ui_OpaBakkebaard	= '<img alt="" style="width: 60px; height: 60px;" src="ui/OpaBakkebaard.gif">';
$ui_paddy			= '<img alt="" style="width: 60px; height: 60px;" src="ui/paddy.gif">';
$ui_Pharkus			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Pharkus.png">';
$ui_Puala			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Puala.gif">';
$ui_Re				= '<img alt="" style="width: 60px; height: 60px;" src="ui/Re.gif">';
$ui_rene90			= '<img alt="" style="width: 60px; height: 60px;" src="ui/rene90.jpg">';
$ui_Renesite		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Renesite.png">';
$ui_RockabeIIa		= '<img alt="" style="width: 60px; height: 60px;" src="ui/RockabeIIa.jpg">';
$ui_rubbereend		= '<img alt="" style="width: 60px; height: 60px;" src="ui/rubbereend.jpg">';
$ui_Sack_Blabbath	= '<img alt="" style="width: 60px; height: 60px;" src="ui/Sack_Blabbath.gif">';
$ui_SaintOfKillers	= '<img alt="" style="width: 60px; height: 60px;" src="ui/SaintOfKillers.jpg">';
$ui_senesta			= '<img alt="" style="width: 60px; height: 60px;" src="ui/senesta.jpg">';
$ui_shmoopy			= '<img alt="" style="width: 60px; height: 60px;" src="ui/shmoopy.jpg">';
$ui_SiIk			= '<img alt="" style="width: 60px; height: 60px;" src="ui/SiIk.gif">';
$ui_sitting_elfling	= '<img alt="" style="width: 60px; height: 60px;" src="ui/sitting_elfling.jpg">';
$ui_Sjeen			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Sjeen.jpg">';
$ui_Snakey			= '<img alt="" style="width: 60px; height: 60px;" src="ui/Snakey.jpg">';
$ui_Sounddragon		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Sounddragon.gif">';
$ui_sp3c			= '<img alt="" style="width: 60px; height: 60px;" src="ui/sp3c.jpg">';
$ui_Specularium		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Specularium.gif">';
$ui_static 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/static.gif">';
$ui_Tamashii		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Tamashii.jpg">';
$ui_timmmmm			= '<img alt="" style="width: 60px; height: 60px;" src="ui/timmmmm.jpg">';
$ui_UIO_AMS			= '<img alt="" style="width: 60px; height: 60px;" src="ui/UIO_AMS.jpg">';
$ui_Vonkenboer		= '<img alt="" style="width: 60px; height: 60px;" src="ui/Vonkenboer.jpg">';
$ui_zarGon 			= '<img alt="" style="width: 60px; height: 60px;" src="ui/zarGon.gif">';		   

?>